CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

INSERT INTO users (name, email, password)
SELECT 'Administrador', 'admin@admin.br', '$2b$10$Q4KpE8DKR4s5y3a0c5t5D.2kZ3u4V0pFJ5miI7Q6YkNnKqj7QG3o2'
WHERE NOT EXISTS (
  SELECT 1 FROM users WHERE email = 'admin@admin.br'
);
